eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with_eureka: true
    fetch-registry: true
    service-url:
      deafaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
