eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with_eureka: true
    fetch-registry: true
    service-url:
      deafaultZone: http://eureka-service/eureka/
    instance:
      hostname: eureka-service
