eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    register-with_eureka: true
    fetch-registry: true
    service-url:
      deafaultZone: http://192.168.0.100/eureka/
    instance:
      hostname: 192.168.0.100
